# Generated by Django 4.1.7 on 2023-06-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_event_delete_topic"),
    ]

    operations = [
        migrations.RenameField(model_name="event", old_name="author", new_name="user",),
    ]
