name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip

      - name: Copy code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 3.73.101.33
          username: ec2-user
          key: ${{ secrets.API_INSTANCE_PRIVATE_KEY }}
          source: .
          target: /home/ec2-user/goodraves/CMS-portal-eventowy

      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@master
        with:
          host: 3.73.101.33
          username: ec2-user
          key: ${{ secrets.API_INSTANCE_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/goodraves/CMS-portal-eventowy
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            python manage.py runserver 0.0.0.0:8000
